configs:
  params:
    server.insecure: true


redis-ha:
  enabled: true

controller:
  replicas: 2
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2